[alias]
# This redefines 'cargo test' to always include your feature
test-all = "test --all-features"
ta = "test --all-features"
run-tower-service = "run --example tower_service --features runtime-compression,tower --"
run-tower-middleware = "run --example tower_middleware --features runtime-compression,tower --"

check-windows = "check --all-features --target x86_64-pc-windows-msvc"
open-docs = "doc --all-features --open"
