[alias]
# This redefines 'cargo test' to always include your feature
test-all = "test --all-features"
ta = "test --all-features"
run-tower-service = "run --example tower_service --all-features --"
run-tower-middleware = "run --example tower_middleware --all-features --"
run-hyper = "run --example hyper --all-features --"

check-all = "check --all-features"
check-windows = "check --all-features --target x86_64-pc-windows-msvc"
build-docs = "doc --all-features"
open-docs = "doc --all-features --open"
